version: '3'

services:

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_bank
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  calculator:
    build: calculator/.
    hostname: calculator
    environment:
      CALCULATOR_HOST: calculator
      CALCULATOR_PORT: 8080
    ports:
      - '8080:8080'

  dossier:
    build: dossier/.
    hostname: dossier
    depends_on:
      - kafka
    environment:
      DOSSIER_HOST: dossier
      DOSSIER_PORT: 8083
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      DEAL_HOST: deal
      DEAL_PORT: 8081
    env_file:
      - .env
    ports:
      - '8083:8083'

  deal:
    build: deal/.
    hostname: deal
    depends_on:
      - kafka
      - db
      - calculator
    environment:
      DEAL_HOST: deal
      DEAL_PORT: 8081
      DB_HOST: db
      DB_PORT: 5432
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      CALCULATOR_HOST: calculator
      CALCULATOR_PORT: 8080
    ports:
      - '8081:8081'

  statement:
    build: statement/.
    hostname: statement
    depends_on:
      - deal
    environment:
      STATEMENT_HOST: statement
      STATEMENT_PORT: 8082
      DEAL_HOST: deal
      DEAL_PORT: 8081
    ports:
      - '8082:8082'

  gateway:
    build: gateway/.
    hostname: gateway
    depends_on:
      - statement
      - deal
    environment:
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 8000
      DEAL_HOST: deal
      DEAL_PORT: 8081
      STATEMENT_HOST: statement
      STATEMENT_PORT: 8082
    ports:
      - '8000:8000'
